version: '3.8'

services:
  travelai-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: travelai-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"  # Vite dev server
      - "8000:8000"
      - "9229:9229"  # Node.js debugger
    environment:
      - NODE_ENV=development
      - PORT=8000
      - FRONTEND_PORT=3000
      - FRONTEND_URL=http://localhost:3000
      - API_BASE_URL=http://localhost:8000
      - MONGODB_URI=mongodb://mongodb-dev:27017/travelai_dev
      - REDIS_URL=redis://redis-dev:6379
      - SESSION_SECRET=dev-session-secret
      - JWT_SECRET=dev-jwt-secret
      - DEBUG=travelai:*
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb-dev
      - redis-dev
    networks:
      - travelai-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    command: npm run dev
    stdin_open: true
    tty: true

  mongodb-dev:
    image: mongo:6.0
    container_name: travelai-mongodb-dev
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev123
      - MONGO_INITDB_DATABASE=travelai_dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - travelai-dev-network

  redis-dev:
    image: redis:7-alpine
    container_name: travelai-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    networks:
      - travelai-dev-network

  mongo-express:
    image: mongo-express:latest
    container_name: travelai-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dev123
      - ME_CONFIG_MONGODB_URL=mongodb://dev:dev123@mongodb-dev:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb-dev
    networks:
      - travelai-dev-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: travelai-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis-dev:6379
    depends_on:
      - redis-dev
    networks:
      - travelai-dev-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: travelai-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - travelai-dev-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: travelai-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - travelai-dev-network

networks:
  travelai-dev-network:
    driver: bridge

volumes:
  mongodb_dev_data:
  redis_dev_data: